export const countryOptions = [
  'India',
  'Portugal',
  'Japan',
  'Thailand',
  'Singapore',
  'United Kingdom',
  'New Zealand',
  'Ireland'
];
export const state = [
  'KARNATAKA',
  'MAHARASHTRA',
  'DELHI',
  'GUJARAT',
  'GOA',
  'HARYANA',
  'TELANGANA',
  'PUNJAB',
  'JAMMU & KASHMIR',
  'HIMACHAL PRADESH',
  'CHANDIGARH',
  'UTTAR PRADESH',
  'TAMIL NADU',
  'WEST BENGAL',
  'BIHAR',
  'PONDICHERRY',
  'MADHYA PRADESH',
  'RAJASTHAN',
  'UTTARAKHAND',
  'KERALA',
  'DADRA & NAGAR HAVELI',
  'ODISHA',
  'DAMAN & DIU',
  'ANDHRA PRADESH'
];
export const city = [
  'City',
  'Bengaluru',
  'Thane',
  'West Delhi',
  'Mumbai',
  'Vadodara',
  'North Goa',
  'East Delhi',
  'Gurgaon',
  'Hyderabad',
  'South Delhi',
  'Amritsar',
  'Pune',
  'North West Delhi',
  'Jammu',
  'Solan',
  'Chandigarh',
  'Ahmedabad',
  'Moradabad',
  'Raigarh(MH)',
  'Gautam Buddha Nagar',
  'Ludhiana',
  'South West Delhi',
  'Erode',
  'Kanchipuram',
  'Valsad',
  'Nashik',
  'Sangli',
  'Panipat',
  'Rampur',
  'Kolkata',
  'Patna',
  'New Delhi',
  'Central Delhi',
  'Bangalore Rural',
  'Madurai',
  'Chennai',
  'Tiruvannamalai',
  'Pondicherry',
  'Tumakuru',
  'Tiruvallur',
  'Aurangabad',
  'Surendra Nagar',
  'Mohali',
  'Raisen',
  'Rajkot',
  'Jodhpur',
  'North Delhi',
  'Dehradun',
  'Surat',
  'Jamnagar',
  'Navsari',
  'Jalgaon',
  'Gandhi Nagar',
  'Coimbatore',
  'Kottayam',
  'Jalandhar',
  'Medak',
  'Nagpur',
  'Faridabad',
  'Sonipat',
  'Kachchh',
  'Jaipur',
  'Satara',
  'Anand',
  'Kanyakumari',
  'Nagapattinam',
  'Indore',
  'Kozhikode',
  'South 24 Parganas',
  'Ghaziabad',
  'Dadra & Nagar Haveli',
  'Ernakulam',
  'North 24 Parganas',
  'Akola',
  'Sirmaur',
  'Jyotiba Phule Nagar',
  'Varanasi',
  'Khorda',
  'Lucknow',
  'Dakshina Kannada',
  'Jabalpur',
  'K.V.Rangareddy',
  'Thiruvananthapuram',
  'Daman',
  'Kanpur Nagar',
  'Malappuram',
  'Mahesana',
  'South Goa',
  'Jhajjar',
  'Ujjain',
  'Udaipur',
  'Karnal',
  'Amravati',
  'Thanjavur',
  'Kasargod',
  'Bidar',
  'Krishna',
  'Sabarkantha',
  'Kangra',
  'Allahabad',
  'Hanumangarh',
  'Saharanpur',
  'Bhavnagar',
  'Nilgiris',
  'Visakhapatnam',
  'Bareilly',
  'Meerut',
  'Patiala'
];
